name: pipeline build .NET, run tests, optional deploy to staging environment

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: build project in release
        run: dotnet build --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: run tests
        run: dotnet test --no-build --verbosity normal

  approval:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.ask.outputs.deploy }}
    steps:
      - id: ask
        run: |
          echo "Do you want to deploy to staging environment? (yes/no)"
          read ans
          if [[ "$ans" == "yes" ]]; then
            echo "::set-output name=deploy::true"
          else
            echo "::set-output name=deploy::false"
          fi

  docker-build-push:
    needs: approval
    if: needs.approval.outputs.deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker image
        run: docker build -t httpsrichardy/comanda:staging-latest .

      - name: push docker image
        run: docker push httpsrichardy/comanda:staging-latest

  deploy:
    needs: docker-build-push
    if: needs.approval.outputs.deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to azure container apps
        run: |
          az containerapp update \
            --name comanda-staging \
            --resource-group Comanda \
            --image httpsrichardy/comanda:staging-latest
